connections {
    matriz-to-filial {
        version = 2
        local_addrs = 192.168.122.24
        remote_addrs = 192.168.122.48

        local {
            auth = psk
            id = 192.168.122.24
        }
        remote {
            auth = psk
            id = 192.168.122.48
        }

        proposals = aes256-sha256-modp1024
        rekey_time = 3600s

        children {
            matriz-to-filial {
                local_ts  = 192.168.10.0/24
                remote_ts = 192.168.20.0/24
                esp_proposals = aes256-sha256-modp1024
                rekey_time = 86400s
                mode = tunnel
                start_action = start
                dpd_action = restart
                updown = /usr/libexec/strongswan/_updown iptables
            }
        }
    }
}
